CREATE DATABASE DB_2IPI;

USE BD_2IPI;

/*CRIANDO TABELA SOMENTE PARA ILUSTRAÇÃO, TEM MAIS REGRAS DE RELACIONAMENTO E RESTRIÇÕES */

CREATE TABLE TB_CEP(
    ID_CEP INT PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR (8) NOT NULL,
    RUA VARCHAR (100) NOT NULL,
    NUMERO VARCHAR (4) NOT NULL,
    COMPLEMENTO VARCHAR (50),
    BAIRRO VARCHAR (50) NOT NULL,
    CIDADE VARCHAR (50) NOT NULL,
    UF CHAR (2) NOT NULL
);



